version: '3.8'

services:
  telegram-bot:
    build: .
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
      - DATABASE_URL=postgresql://postgres:password@db:5432/telegramdb
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telegramdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/chatbot-ui:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - telegram-bot


  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.0
    ports:
      - "8001:8000" # Use port 8001 on the host to avoid conflict
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  pgdata:
  chroma_data:
